language: java
services:
- docker
cache:
  directories:
  - "$HOME/.m2"
  - "$TRAVIS_BUILD_DIR/node_modules"
jdk:
- openjdk8
env:
  global:
  - secure: AgVMUXaAb/XM+NmJOaXwyd6u5OKDflvm2SY+QAyAz5VKkI4tDuaPVKOTJ+bAy5gR2Y7naOwCAot2ucLsDnx2NYCh5G6EfLtdF5sH1YD/ZBcCne+ySsSRSQZulJ+7wyNCCCSW1nXzAehq/fVZP4K86KtAGYS+C0OvrCoQx3v69AeqFJmypNBtMdrdXqrEwCb21tRbdOe8vhXMAk2VLtUIvDyj2ZYONaCxoiI70XGSdj3r3gtc3gXpCq0fBWLo3KXhYVlkr9YdLtIBgx/mwvs1CWOS+U9iDn1537/Ag/h4fIZx/wb1EUl/hXnwpX2sUBYp0b7Oy32uhxVni4pPHbAtGUSkUol878jq2chOC3OTR1YD97e27ebZiIWxThdfgC9TpHMwyplb6rjqCVZXczWxJ2qBzoHdmQBwqSqNJJhmwAUQkHGvkA7lz3CPvAubLnPRR9gqmPPY2aWSlCw9xlENcLxnkJom4lkxFTz8FwKnLskGOyJeoETPyeD/wHR/pULj7DzNTMRDhCsZID1vSuEDPi5xeCzZs3WgZvRt/EX4K5LNfo2mstuCfIf5wF77duWrbRaNLhsfQt006UbcwsyOeXLipJcLL+0sZ9yzdJ0fGN/a8ByMxq26rnZunULLZ/8zglxeUPfkQLVG6mHTCpOHiR9D1bLsYRFXFRDYa6/rDr0=
  - secure: Tg/OWV+TixAEomzVmxxckqshmtVZTCbEHdozwsdpeOnxEf92NVcfLFLxto31ln4sY/RfcAF7V7f3ePa9KHnbCXx8AsNdmPzFwA3cB7jNVVBxS0dqMBSm63FjNApkIkty3LB9YNpCyRe6eu9cEBXwoXo6Ls9XoINcWKYzqlhiv8Kx1hXsyD2sV7D31lY3MirsVbbTu6+0jxRCyRM0w9NUWWXuEV83NpMuJwKGzvqTROELghW6CNvRXENZON1f0m7udKlCB0uC9VwRtZoKXqmfJ5bk9OntWF2YggEEZ5jBRhPDLRXTSx0EI0DoXZc1bhBfQWK5ZRsShFHvVZVRl7YLrKe7GaIf6ITm0I9WdIY6X5dZu5DoJ/v//+0sncowQTQPZ0YsM1GhwDoFGSvZfo5Mr3423EogYlFU9nrBsx4DrxlxHdEMwB69yWvyHfY4GeVpypjryeuCo1gLLtjPt1BQP2V9ixd4ixZLdqqI1a9QK1TJgRjtxQdQY9zDFQgurcrQj8lnzYB7bhiO2DTf+9pm7irJgessI8jNHNPnuHk+HQWbSn9MTmENRIGhDlm7I0+iXT2y33F/F9bqJR7dSUT1w1gULdsif5S+lmfMsFgPqnZziiExroScefjXqzOkDqqGM4mGhNyVcaKux0rXXo+7GsjKkgodF9rvF6p2D08fMqQ=
  - SECRATDOCKERREPO=securityrat/securityrat
before_install:
- sudo apt-get update
- sudo curl -sL https://deb.nodesource.com/setup_12.x | sudo bash
- sudo apt-get install nodejs
- sudo apt-get install build-essential
- sudo npm install -g bower grunt-cli
stages:
- test
- name: deploy
jobs:
  include:
  - stage: test
    script:
    - mvn clean test
  - stage: deploy
    script:
    - mvn clean
    - mvn -Pprod -DskipTests package
    - export WAR_FILE="$(ls target/ | egrep .*\.war$)"
    - export NAME="$(echo $WAR_FILE | egrep -oh '(.*)[^\.war]')"
    - export TAG_NAME=$(git describe --exact-match)
    - chmod +x createArchive.sh
    - "./createArchive.sh"
    before_deploy:
    - export RELEASE_ZIP_FILE=$(ls target/*.zip)
    - export RELEASE_TAR_FILE=$(ls target/*.tar.gz)
    deploy:
      provider: releases
      api_key:
        secure: h5VXEniWJq45I5/YAWBdJXR1rSxvIf0coME3UlOVgykpgFyzqgRD/ToM8m/Kh9I4I8L/Is+YrkAM+goTf+YOj/6d6/sUnNXGrm1DUykL8C4xJkRdKA2Ukyo3r20buPtQszMJ2R0yEcWPqsIw2yqCF8oo33T7Q2BXrmj5d3lNRJMFED2znaW1xuNUTQKDjQwszsNOh72djPklRdrAlkhA3pal1SEnfyeV/qKZXbTEPPbmPpX94X/k+z6k4LPww1Ssi3a49eSuJY3Y2urIrVg9MN8DFIcY0eGqMSG4R2sPu3Up47sSsIRCQBewDcEcR8uZSZ0A93Op1gKnADg6X11ynrFlggChqkRKVmcNVlICV2Lg2Z4/05Iu/It1ZQNarCGJB6FuCANMZCCVYpXmtrZ2Q6xBqTX/qHwHl/MssofUgx1RglUhixiSoufSWWobC5p5GJlyyzBRb/eObjvnoOxgYMlIsLh32dKj5SXkk/NVUFvcsPLnNRH/vdPTvnBlOeV+R2019+0QK/o7LKh10b6x4o2yHOSXIovDdLJe/rfoezvEJpzXxUeBT8ZTAGCoZ9jlUG1z6tqTQB5pOyqAUtdTSHP1ybhigA2381HE+ETp/FAJR4YOsJ8kROHR3NLdF0d3iMsGtSWK0S65PIsg7vA673GWf0pEP+0mK7X0O9SKXy4=
      skip_cleanup: true
      file_glob: true
      file:
      - "${RELEASE_ZIP_FILE}"
      - "${RELEASE_TAR_FILE}"
      on:
        repo: SecurityRAT/SecurityRAT
        branch: master
        condition: "-n $TAG_NAME"
    after_deploy:
    - chmod +x afterDeploy.sh
    - "./afterDeploy.sh"
