sudo: required
language: java
services:
- docker
cache:
  directories:
  - "$HOME/.m2"
  - "$TRAVIS_BUILD_DIR/node_modules"
jdk:
- oraclejdk8
env:
  global:
  - secure: dP+91bNqFEiNgVaSamaYPVYozytHbXCM2Cdy4n2aFzcWPE/rhZFaFsKOFhzM9PXhvPGQREgu/4UEnxpghBqL92fKedGAToBeLzIGQQeLW6schlpzUrspTAHRdq5faEF1RZ/K1CDVTpgugx0gAZv7iIgcD1uzSDoHLCjrwtyZlGFTj7EOt8OfAWZuL9ibfPcvr7/wu3fEnAaQMYPMeG23uaFq5/FxfWyha1Arq2noe8BoChi8210FGspldv5Ni+M2rad6eG0nu1SxZU5apfMdBBR4l4DOPSQRhvK2AZ7Xoi898aPSXGeBnNt79lcwAqdtALWkAWzvY8oMJP/8Khj0mWuGkr2/85CoPE8naVkmHbHGTx6Hfd3iZAml1G4DE8SgEeBtpeUbxoGlBqrZgEyukmXJX3GXfVWdZn0nq7+UHqpph0qONcFl7k0R8nuRQLEQb9SJh+T4DSrwBcfL+LMKw7Yluw8zyLtHMaK0URIBObE0LSNfSXGCnOLtYFUCRwHi9kkenOyHJp2M3+5FwprF7zcEg7mrZg86wXSmDGP4ZzB4sdJIHeJu9cKYr6KmNZceI5MQIzKu2XzZkQ+8AhfOerEDEfWg8mz4bX86GqEM5nQ0+ecmjwtL2H2SitxZj1C3Vb07GBzbRqHIDkj1z+6/k+/rooEfgosZp4Xw/igf9tc=
  - secure: gkU5PvUys90HGR4hc27hpqWUCJnbXpwBoYZr2Qminkyy0sj/oVH5+eQhUePWFbX4D0tlKyikTHHfblGwAdLacXyD24IzgBWPBylDSK6f5p/eEamGhJ/NymsR/6qR9lqCw0FyCb2vA4nke9CZrCRgQATdU6HDLlEyGzcCqEXpWzQFZEBQMvlEJoQ6/LaagxbLWuYdJJqntiYgNUJTx08i1Rq3dk9XzDp/AUNy0ZycQkOH3TR5qO5tFC9RwAFRDc93apZAb2uEg0x1Y6UR+p1p78R4BpPyen1Is06jLiSCU61IymzJsxmhUxDYKTyrpCRDycM+eKw2+3mRFLIQRk1vjczUFwG4w5cX/7JLiVuSZty4Oweqif7xW+kL4/53VT9yIQ8PnoxPfAUL1XuXheC3P+x+EZH4bAv3XnI295TVIuK/UD/WUMBu1xCLgU73USiyy9aP8oTKrfYhVVeFTsh8oO4xiZq1902V8FznkwBO4eo2w9l/dvbbf0PNck2HCPCM54Ybh3Ile3l8JUphD8FkYNAZiWE2eOm50rF2jYJAlwLBurYtIG+yEnvt235hSwUyzVye88TBTqYp5yhYNlEVeYP9JKpSoB8ttgLo8B5MsytMNYnrjfBW9ZclDZU/32/UmbMCP0IRIwA/wjMj2g0QuJeynLL/kLUqC8gRCNl7oz4=
before_install:
- sudo apt-get update
- sudo curl -sL https://deb.nodesource.com/setup_4.x | sudo bash
- sudo apt-get install nodejs
- sudo apt-get install build-essential
- sudo npm install -g bower grunt-cli
script:
- mvn -Pprod package
- export WAR_FILE="$(ls target/ | egrep .*\.war$)"
- export NAME="$(echo $WAR_FILE | egrep -oh '(.*)[^\.war]')"
- export TAG_NAME=$(git describe --exact-match)
- chmod +x createArchive.sh
- "./createArchive.sh"
branches:
  only:
  - master
before_deploy:
- export RELEASE_ZIP_FILE=$(ls target/*.zip)
- export RELEASE_TAR_FILE=$(ls target/*.tar.gz)
deploy:
  provider: releases
  api_key:
    secure: fkTZAqgYUwDD6WzQ3ZyUleYEW2X/F4PU3iRp9UhfxIvk0OMsZ5pqWHTgYzgg2b49vSV93dCBZFYnTlUwT3aQBWAyGDNJ5/l3JNrjD2DZOsRia5tijXJB6X3e4QSY2U8XzA5AVxZ3kDYE5NzRf0usw6+NwYooAHHqglDGbUdIB9QNqfm5XQFYL4KpD1XsGA3UYVYDiMGDi5nWO+BKQD0hGN6w3oSQf40CDik2lPVWGfpdlYnUcF8Ii0ko5tHCFblvNeVcT9pRsMQaSbo/5UsszUaW0/cvOpbfeNnwp914s5OoqXCP22vZaFapbsW0cEa+yNSOs2b4oBhl+nR2vV6Txm4g9zpX3/2Jz9ZvwZCr8k3HMUl1HQoXR0gNJsg308O3AkdZLnEqb9nVCtmRC1x89AI5idye5GwIlfq1woS5yb7Zno8v1O+pZA3/tMqiwSElWQFtMtZFAF2xD0eD3QJ4uaXwjSR5lc5z11vPsFMfRYa8Bj/Nhnt3q+HAulTzArS5R6OQiAfopcGc1j9tFiNG6dJBZ+UJ1Nl8mflectXiq4mfPuVvVHSSjiPFptFxAwz1589bWBJft5lQAx8BPyO9jU7yUGZl3PIIOhszSHrQkwQ7fZq7NhploI414AGtowYM6Z0o26XNJDiC44c+alVZKq1bQaucc27mC4F5RwX29G8=
  skip_cleanup: true
  file_glob: true
  file:
  - "${RELEASE_ZIP_FILE}"
  - "${RELEASE_TAR_FILE}"
  on:
    repo: rylyade1/SecurityRAT
    branch: master
    condition: "-n $TAG_NAME"
after_deploy:
- chmod +x afterDeploy.sh
- "./afterDeploy.sh"
